name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the deployable artifact failes
        required: false
        default: dist
        type: string
    outputs:
      result2:
        description: The result of the deployement
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result=SUCCESS" >> $GITHUB_OUTPUT
